### ISSUE TITLE
Photon fails to load with: error loading dynamically imported module

### ISSUE THREAD

**Issue by CTalvio** [Xyphyn/photon#253]
**Describe the bug**
After updating to the new release, photon may fail to load.

Browser console displays an error: `Uncaught (in promise) TypeError: error loading dynamically imported module: https://photon.domain.com/_app/immutable/nodes/0.CNSbv_Eb.js` exact .js file varies.

**To Reproduce**
1. Set up Photon
2. Clear cache
3. Try to load various pages in photon (with clear cache)

**Expected behavior**
It should work, as before.

**Versions**
- Browser: Firefox
- Photon version: 1.27.0

**Comment by nsakkos** [comment]
I am experiencing a similar problem, but with HAProxy and photon running in a docker container. I can access the page directly, but HAProxy marks it as being down and removes the photon container from the backend pool as soon as I launch it (specific error from HAProxy logs "Layer 7 timeout in 2001ms").

**Comment by poVoq** [comment]
Photon in Podman container, with Nginx in front, but no such issue.

Sounds like an reverse-proxy configuration issue to me.

**Comment by CTalvio** [comment]
> Photon in Podman container, with Nginx in front, but no such issue.
> 
> Sounds like an reverse-proxy configuration issue to me.

Would mind including whats different between out configs, then?

**Comment by CTalvio** [comment]
More info, problem only occurs in firefox/librewold. Chromium is not affected.

Issue does not seem to be related to extensions, will continue to investigate.

**Comment by CTalvio** [comment]
> is a 404 crashing it or something

It's not crashing. Error is a 500, and sometimes rarely Photon does load, but then certain pages display this:

![image](https://github.com/Xyphyn/photon/assets/4365015/3dc50eb4-3c52-4a50-9ff5-a19476e7f734)

Doesn't occur in Chromium. Something about firefox is borking it up.

**Comment by poVoq** [comment]
It definitely works in Firefox here.

Probably some extension you have installed?

**Comment by Demigodrick** [comment]
+1 here:

![image](https://github.com/Xyphyn/photon/assets/117108241/642f948d-d630-4013-8a4f-1d56acb55d10)

Same on firefox desktop and mobile.

On chrome mobile i just get a spinning icon.

**Comment by poVoq** [comment]
Can you try our instance at https://photon.slrpnk.net

If that works I'll try to figure out the difference in the nginx config.

**Comment by CTalvio** [comment]
Yup, that works.

**Comment by poVoq** [comment]
```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    ssl_certificate /etc/letsencrypt/live/photon.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/photon.example.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/photon.example.com/chain.pem;

    server_name  photon.example.com;

    location / {
        proxy_pass http://127.0.0.1:3000;

        # Pass on information about the requests to the proxied service using headers
        proxy_set_header HOST $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```
Is what I have. Seems simpler, but otherwise similar.

**Comment by CTalvio** [comment]
Matching your config does not seem to have helped :(

**Comment by CTalvio** [comment]
Something is REALLY weird here. It has actually started loading, but a lot of pages still net the 500 error about a module failing to load. I just restarted firefox without extensions, no change, but coming back to normal mode a lot more pages worked again.

So next I decided to try clearing cache.

Everything broke. Now it doesn't load at all again and it's back to just a white page. It's like it somehow managed to cache some modules over time and that allowed it work and clearing it broke it completely again.

**Comment by CTalvio** [comment]
Unfortunately increasing the buffers doesn't seem to have helped.

The problem only occurs in firefox/gecko. Desktop, librewolf, mobile. Functionality improves over time, somehow, as files are cached, but clearing cache reduces photon to a blank white page, and is how it appears when first loading it with a blank cache.

Chromium based browsers work just fine.

Oddly enough, lemdro.id works, only my own photon instance doesn't.

**Comment by pbui** [comment]
I am also experiencing the same issues as @CTalvio .  Even after increasing the buffers as mentioned by @CorvetteCole, I am still experiencing the 500 error on Firefox (Android). After refreshing a few times, it eventually works, but that is not a good user experience.

On the desktop, I no longer receive the errors, but I did a few times before increasing the buffer sizes.

**Comment by CTalvio** [comment]
@pbui If you clear browser cache, does photon break again? I can also get things to work by repeatedly refreshing until photon is loaded into cache, but this _really_ isn't ideal, and not an actual solution.

**Comment by Demigodrick** [comment]
Out of curiosity are either of you using cloudflare?

**Comment by CTalvio** [comment]
Also no cloudflare.

**Comment by Demigodrick** [comment]
I also get this error in the photon container logs:

```
error: Not found: /index.html

      at new SvelteKitError (/app/build/server/chunks/index.js:37:5)

      at /app/build/server/index.js:2774:18

      at resolve2 (/app/build/server/index.js:2670:27)

      at resolve (/app/build/server/index.js:2606:43)

      at /app/build/server/chunks/hooks.server.js:73:26

      at handle (/app/build/server/chunks/hooks.server.js:8:22)

      at /app/build/server/index.js:2604:28

32 |    * @param {number} status

33 |    * @param {string} text

34 |    * @param {string} message

35 |    */

36 |   constructor(status, text2, message) {

37 |     super(message);

         ^
```

**Comment by Demigodrick** [comment]
Does adding PUBLIC_SSR_ENABLED=true help at all?

**Comment by CTalvio** [comment]
Increasing the buffer size maybe speeds up the process of getting things to work by repeatedly refreshing, but no matter how big I set it, with a cleared cached the "first" load fails completely.

**Comment by CTalvio** [comment]
> PUBLIC_SSR_ENABLED=true

Well something changed. That does allow the page to load. But...

![Screenshot_20240223_194921](https://github.com/Xyphyn/photon/assets/4365015/49de7189-ec08-419c-abc5-b55c632bc4f6)

**Comment by CTalvio** [comment]
Soooooooo I just got the the same 500 error accessing via IP:PORT, which means this error can apparently happen when just accessing the photon docker directly, and that nginx, rather than causing it, makes it worse???

**Comment by Demigodrick** [comment]
Yeah i think the same is happening to me, although it lets the page load on the ip:port but is still broken in that none of the options work and the same error is in the console

**Comment by CTalvio** [comment]
![image](https://github.com/Xyphyn/photon/assets/4365015/2466924a-a3a6-447a-8d12-b8b9d919508a)

It doesn't happen nearly as much, but, if I go to my profile, clear cache, reload, that page fails to load consistently, even with direct ip:port, no nginx in-between.

**Comment by Demigodrick** [comment]
interestingly on IP:PORT i now get this error:

`Loading module from “http://ip:port/_app/immutable/chunks/auth.r4SQ5gui.js” was blocked because of a disallowed MIME type (“”).`

**Comment by CorvetteCole** [comment]
> No, I'm not using cloudflare. I just have nginx proxying to a docker container on the same box.
> 
> This looks related to: [sveltejs/kit#11084](https://github.com/sveltejs/kit/issues/11084)

that is definitely what lemdro.id hit. For what it's worth, lemdro.id works great now and photon is behind nginx and cloudflare

**Comment by CorvetteCole** [comment]
we saw some issues with dynamically imported modules early on but was fixed by redeploying the docker container. maybe try that?

**Comment by CTalvio** [comment]
> we saw some issues with dynamically imported modules early on but was fixed by redeploying the docker container. maybe try that?

This doesn't seem to have made any difference.

**Comment by weiteck** [comment]
I have a similar issue. although with different versions. With a similar nginx config as other front-ends, it works fine on v1.27.0 but updating to anything later results in a blank page with console error: ```Uncaught (in promise) TypeError: error loading dynamically imported module: https://photon.domain/_app/immutable/entry/start.J_4MMBrP.js``` I'm not sure what changed with v1.27.1 to cause this.

**Comment by Ategon** [comment]
Looks like the javascript files are being sent with a content header of text/html rather than application/javascript. Should be an easy ffix by sending the correct one

**Comment by Demigodrick** [comment]
So the text/html is most likely nginx returning an error page rather than anything being sent incorrectly.

Considering the site works directly via ip:port (after a refresh - so there is still an error here) then i'm circling back around to it being an nginx thing or a docker container thing.

**Comment by CTalvio** [comment]
@Demigodrick I was able to get it to happen even without nginx in-between. It just happens a lot more on nginx, and only in firefox. Chromium based browsers are fine.

**Comment by Demigodrick** [comment]
For me it breaks on Chromium too (beta.lemmy.zip) 

![image](https://github.com/Xyphyn/photon/assets/117108241/565082e6-0d17-4689-a07c-97c8c4b1985d)

Kind of stuck without @Xyphyn giving us some more debug options or someone being able to point out why some version of nginx work and others don't.

Something somewhere is causing the 502 error (which i suspect is causing the html/js mismatch errors when the 502 page is returned.)

There was a change to bun in the version where it stopped working, so it might have something to do with that.

**Comment by 0xAnansi** [comment]
Had the same issue.

Seems that it's an issue between Svelte and most default proxy configs.

The fix consists in allowing bigger headers.

Added this in my instance nginx config and that fixed it:

```
server {
...
proxy_busy_buffers_size   512k;
proxy_buffers   4 512k;
proxy_buffer_size   256k;
...
}
```

**Comment by CTalvio** [comment]
@0xAnansi Was already brought up, i tried it, is to not a fix.

**Comment by 0xAnansi** [comment]
Could it be related to the use of bun instead of Node?

I  don't see anything else that could lead to this behavior in the changelog between 1.26 and 1.27 except this. I rolled back to 1.26 and everything works as intended.

**Comment by 0xAnansi** [comment]
Some more information in care it can help someone debug.

First installed version was 1.27.0, worked out of the box.

Upgraded to 1.28.3 and started seeing issues with Firefox. Added SSR_ENABLED in config and made the buffers bigger in Nginx solved most of the issues but some dynamic scripts failint to load/generate, returning a 500 error.

Downgraded to 1.26.0 then 1.25.0 and it worked until I cleared the cache, then had the same issue than the 1.28.3.

Returned to 1.27.0 and everything seem to work again, even after a cache clear.

I noticed than on first load of the buggy versions after clearing the cache, almost nothing works and it needs a second reload to get it mostly working.

**Comment by Demigodrick** [comment]
There is a definite issue since moving to bun from node, but I can't figure out what is causing it.

Im running it in a different container on a different url and still have the same issue, despite clearing my cache, trying different computers etc.

As some people have got this working, it is narrowed down to a server side issue, but what that issue is I cannot get to the bottom of and really we need help from @Xyphyn to figure out why this is.

**Comment by CorvetteCole** [comment]
I want to know if this happens when running outside of docker. on lemdro.id, everything works fine but we unpack the OCI images into VMs

**Comment by Xyphyn** [comment]
I will add an option to allow people to use the node server instead of bun

**Comment by Xyphyn** [comment]
I need help debugging this. What is your setup right now? When I run directly with the command, it runs fine. What proxy are you using?

**Comment by Demigodrick** [comment]
Ubuntu server, nginx as the reverse proxy. Similar nginx config to the one posted higher up in this thread.

Worked (still works fine) on 1.26.0. Upgrading past this version causes the issues, which appear to be when bun was implemented.

Docker on the latest version. 

Happy to share any other info.

**Comment by Xyphyn** [comment]
are you using nginx in docker compose or standalone?

**Comment by CTalvio** [comment]
I am not using nginx in a container.

**Comment by weiteck** [comment]
I have a similar standalone nginx setup:

- photon.leminal.space working with v1.27.0
- photon-test.leminal.space is the latest version and seems to work in Chrome but not Firefox

**Comment by Demigodrick** [comment]
Mine is containerized (originally as part of lemmy-ansible)

**Comment by Demigodrick** [comment]
Unfortunately appears to have come back - so could really do with a node server version.

**Comment by Demigodrick** [comment]
I thought it was broken but might have worked it out - it was nginx.

Increased the rate limiting and it works again.

Might be worth trying that for anyone still stuck. Set mine to 50r/s and a burst of 100.

**Comment by CTalvio** [comment]
I don't have a ratelimit set, and configuring one with the parameters you suggest doesn't fix things.

I don't have the option of easily upgrading the distro version, but I don't see why that should matter. What is the actual change that breaks things on 22.04?

**Comment by Demigodrick** [comment]
On the bun github page under Install (https://github.com/oven-sh/bun?tab=readme-ov-file#install) they have a bit around minimum kernel requirements - do you know what version you're on?

**Comment by CTalvio** [comment]
6.5

**Comment by Demigodrick** [comment]
I'm not sure what it is then, i suspected it was the kernel but if you're already on 6.5 it must be something else.

You could always try https://github.com/asimons04/Tesseract - its built on photon and apparently the dev is active again. You can pull the InfiniteScroll branch to get the latest version.

**Comment by CTalvio** [comment]
Welp. This problem has gone away.

**Comment by 0xAnansi** [comment]
Not for me, had to switch to a fork since I couldn't update Photon anymore and the version used was unstable.

----- Original message -----

**Comment by CTalvio** [comment]
What do you mean?

If you're not updating photon, or even using it anymore having switched to a fork, how would you know whether it'd still be borked for you?

I'm on the latest version, everything works, closing issue.

**Comment by 0xAnansi** [comment]
Because I tried the latest build 2 days ago before switching for the time being.

I'll test it after a new build on another subdomain since it takes 5mn to spin up.

----- Original message -----

**Comment by quazar-omega** [comment]
Does anyone know if any intervention is needed to make it work again?

**Comment by Xyphyn** [comment]
Node servers are now offered for people who can't run the Bun server.

instead of `ghcr.io/xyphyn/photon:tag`, do `ghcr.io/xyphyn/photon:tag-node`

**Comment by Ategon** [comment]
Thanks for the additional node support, tested with programming.dev and its working so will upgrade our version of the frontend off of the pre-bun version
